apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-demo
  description: An example of a Backstage application.  
  annotations:
    github.com/project-slug: floriandorau/backstage-demo
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: mail@dorau.dev
  lifecycle: experimental
